name: On push

on: push

jobs:
  run-checks:
    runs-on: ubuntu-latest

    steps:
      - name: Check out commit
        uses: actions/checkout@v3

      - uses: pnpm/action-setup@v4.0.0

      - name: Use Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
          cache: pnpm

      - name: Run checks
        run: |
          pnpm install --frozen-lockfile
          pnpm build
          pnpm lint
          pnpm test

