name: On release

on:
  release:
    types: [created]

jobs:
  publish-to-npm:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Check out commit
        uses: actions/checkout@v3

      - name: Set up pnpm
        uses: pnpm/action-setup@v2.2.4

      - name: Set up Node 18
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          registry-url: https://registry.npmjs.org

      - name: Produce dist
        run: |
          pnpm install --frozen-lockfile
          pnpm build

      - name: Publish to npm
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
